#!/sbin/sh
# Init script for tailscaled.

. /lib/svc/share/smf_include.sh

TAILSCALED=$(svcprop -p application/binary $SMF_FMRI)
case "$1" in
start)
	smf_clear_env
	"${TAILSCALED?}" &
	;;
stop)
	smf_kill_contract $2 TERM 60
	"${TAILSCALED?}" --cleanup
	;;
*)
	echo "Usage: $0 {start|stop}" >&2
	exit 1
	;;
esac

exit $SMF_EXIT_OK
